spring:
  application:
    name: spring-ai
  ai:
#远程大模型
    # 阿里云百炼  通义千问模型
    dashscope:
      api-key: sk-4c41d490f36c4c5daaf0c3bb4447c5c9
    #本地大模型
    # 本地ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
server:
  port: 8080

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug  #指定包的日志级别
    com.dongguo.spring: debug